mbbapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from mbbapp import views

urlpatterns = [
    url('^$',views.index,name='index'),
    url('^login/$',views.login,name='login'),
    url('^register/$', views.register, name='register'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^list/$',views.list,name='list'),
    url(r'^detail/(\d+)/$',views.detail,name='detail'),
    url(r'^logout$',views.logout,name='logout'),
    url(r'^uploadhead/$',views.uploadhead,name='uploadhead'),
    url(r'^buy/$',views.buy,name='buy'),
    url(r'^reduce/$',views.reduce,name='reduece'),
    url(r'^checknum/$',views.checknum,name='checknum'),
    url(r'^checkone/$',views.checkone,name='checkone'),
    url(r'^checkall/$',views.checkall,name='checkall'),
    url(r'^adv/$',views.adv,name='adv'),
    url(r'^order/$',views.order,name='order'),
    url(r'^orderdetail/$',views.orderdetail,name='orderdetail'),
    url(r'^getorder/$',views.getorder,name='getorder'),
    url(r'^concer/$',views.concer,name='concer'),
    url(r'^pay/$',views.pay,name='pay'),
    url(r'^notifyurl/$',views.notifyurl,name='notifyurl'),
    url(r'^returnurl/$',views.returnurl,name='returnurl'),
    url(r'^select/$',views.select,name='select'),
    url(r'^selectprice/$',views.selectprice,name='selectprice'),
]

untitled/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('mbbapp.urls',namespace='mbb')),
]

templates/adv.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
	<title>我的购物车-麦包包</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css"/>
	<link rel="stylesheet" type="text/css" href="/static/css/cart.css"/>
	<script src="/static/js/jquery-1.12.3.js"></script>
	<script src="/static/js/jquery.cookie.js"></script>
	<script src="/static/js/cart-jq.js"></script>
        <link rel="stylesheet" href="/static/css/adv.css">
        <script src="/static/js/adv.js"></script>
        <style>
            .goods-list tbody tr td{
                text-align: center;
            }
            .goods-list thead tr td span{
                height: 30px;
                width: 30px;
                font-size: 30px;
                margin: 5px;
                cursor: pointer;
            }
        </style>
	</head>
	<body>

		<div class="cart-top">
			<div class="cart-warp">
				<a href="{% url 'mbb:index' %}" class="cart-logo"><img src="/static/img/index/logo.png"/></a>
				<div class="cart-title">
					<h1>购物车</h1>
					<div class="login-bar">您好，欢迎来到麦包包！</div>
				</div>
				<div class="cart-step">
					<div class="cart-step-icon"></div>
					<ul>
						<li><em class="red">1.确认采购商品</em></li>
						<li>2.填写收货信息</li>
						<li>3.支付</li>
						<li>4.支付成功</li>
					</ul>
				</div>
			</div>
		</div>

		<div class="container-bg-warp">
			<div class="container-warp">
				<div class="cart-notice">
					<strong>温馨提示：</strong>
					<p>加入购物车的商品无法为您保留库存，请及时下单购买，商品价格以订单提交时的价格为准。</p>
					<i class="arrow-b-l"></i>
				</div>

                <div class="cart-main">


                    <div id="js-goods-container">

                           <p style="font-size: 30px">收货地址:</p>
                            <div style="font-size: 20px">
                            <select name="sheng" id="sheng">

                            </select> &nbsp;&nbsp;
                                <select name="shi" id="shi">

                                </select>
                                <select name="xian" id="xian"></select>
                                <br>
                                详细地址： <br>
                                <textarea style="width: 380px;height: 90px" name="adv" id="detail">

                                </textarea>
                                <br>
                               联系电话: <input type="text" name="tel">
                            </div>
                            <input type="button" value="提交订单" id="on">

                    </div>

                </div>

			</div>
		</div>
		<div class="footer">
			<div class="footer-warp">
				<div class="special-service">
					<ul>
						<li><a href="javascript:void(0);" class="spe-ser-1"></a></li>
						<li><a href="javascript:void(0);" class="spe-ser-2"></a></li>
						<li><a href="javascript:void(0);" class="spe-ser-3"></a></li>
						<li><a href="javascript:void(0);" class="spe-ser-4"></a></li>
						<li><a href="javascript:void(0);" class="spe-ser-5"></a></li>
					</ul>
				</div>
				<div class="copyright">
					©2007-2012 Mbaobao All Rights Reserved. 嘉兴市麦宝科技信息有限公司 版权所有，禁止非法复制 <a href="javascript:void(0);" class="gray">经营许可证编号：浙B2-20100425</a>
				</div>
			</div>
		</div>
		<div class="fd-side">
			<ul>
				<li><a href="javascript:void(0);" class="chat"><i></i><span>在线咨询</span></a></li>
				<li><a href="{% url 'mbb:cart' %}" class="gocart"><i></i><span>去购物车</span></a></li>
				<li><a href="javascript:void(0);" class="qrcode">
					<div class="qrcode-hover-show"><img src="/static/img/index/ewm_02.png"/></div>
					<i></i><span>二维码</span></a>
				</li>
			</ul>
		</div>
	</body>
</html>

templates/cart.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
	<title>我的购物车-麦包包</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css"/>
	<link rel="stylesheet" type="text/css" href="/static/css/cart.css"/>
	<script src="/static/js/jquery-1.12.3.js"></script>
	<script src="/static/js/jquery.cookie.js"></script>
	<script src="/static/js/cart-jq.js"></script>

        <style>
            .goods-list tbody tr td{
                text-align: center;
            }
            .goods-list thead tr td span{
                height: 30px;
                width: 30px;
                font-size: 30px;
                margin: 5px;
                cursor: pointer;
            }
        </style>
	</head>
	<body>

		<div class="cart-top">
			<div class="cart-warp">
				<a href="{% url 'mbb:index' %}" class="cart-logo"><img src="/static/img/index/logo.png"/></a>
				<div class="cart-title">
					<h1>购物车</h1>
					<div class="login-bar">您好，欢迎来到麦包包！</div>
				</div>
				<div class="cart-step">
					<div class="cart-step-icon"></div>
					<ul>
						<li><em class="red">1.确认采购商品</em></li>
						<li>2.填写收货信息</li>
						<li>3.支付</li>
						<li>4.支付成功</li>
					</ul>
				</div>
			</div>
		</div>

		<div class="container-bg-warp">
			<div class="container-warp">
				<div class="cart-notice">
					<strong>温馨提示：</strong>
					<p>加入购物车的商品无法为您保留库存，请及时下单购买，商品价格以订单提交时的价格为准。</p>
					<i class="arrow-b-l"></i>
				</div>

				<div class="cart-main">
					<div id="js-goods-container">
						<table class="goods-list">
							<thead>
								<tr>

						{# 1	 #}		<th width="100" style="text-align: left"><div class="no" style="float: left" isselect="false">√</div><div style="float: left;line-height: 20px;">全选</div></th>
                        {# 2	 #}		<th width="*" style="text-indent: 80px; text-align: left;">商品名称</th>
                        {# 3	 #}		<th width="90">单价</th>
                        {# 4	 #}		<th width="120">数量</th>
                        {# 5	 #}		<th width="110">小计</th>
                        {# 6	 #}		<th width="50">操作</th>
								</tr>


							</thead>
							<tbody>

                            {% for cart in carts %}
                            <tr class="quantity">
                            <td class="goods-list-td1" style="position: relative;"><div class="no" isselect="{{ cart.isselect }}" isid="{{ cart.id }}">√ </div><img src="{{ cart.good.heading }}"></td>
                            <td class="goods-list-td2">{{ cart.good.name }}</td>
                            <td class="goods-list-td3">{{ cart.good.price }}</td>
                            <td class="goods-list-td4">{{ cart.num }}</td>
                            <td class="goods-list-td5 price1"></td>
                            <td class="goods-list-td6"><span class="reducegood" isid="{{ cart.good.num }}">-</span>  &nbsp;&nbsp;<span class="addgood"  isid="{{ cart.good.num }}">+</span></td>
{#                            <td class="numid" style="position: absolute;left: 0;right:0;z-index: -1;">{{ cart.num }}</td>#}
                            </tr>
                            {% endfor %}
							</tbody>
						</table>


				<div class="cart-pick-other">  您还没有挑选商品，赶快行动吧！<a href="{% url 'mbb:index' %}">马上去挑选商品>></a></div>

                    </div>
					<form action="" method="post">
						<div class="list-footer-info">
							<div class="sale-pane">
								<div class="s-p-line">
									<div class="s-p-title">优惠券/现金券：</div>
									<div class="s-p-input">
										<input type="text" class="input-select-coupon"/>
										<input type="button" value="使用" class="coupon-btn"/>
									</div>
									<a href="javascript:void(0);" class="s-p-lower">优惠券/现金券使用规则</a>
								</div>
								<div class="s-p-line">
									<span class="coupon-verify red">请输入正确的优惠券或现金券编码</span>
								</div>
								<div id="coupon">
									<div class="s-p-line">
										<div class="s-p-title">麦豆：</div>
										<input type="text" value="0" class="md-input"/>
										<span class="md-count">X 10 = <strong class="red"><span id="md-count-reslut">0</span> 个麦豆</strong></span>
										<div class="s-p-lower s-p-lower1">-￥<span id="md_cash">0.00</span></div>
									</div>
									<div class="md-tip s-p-line">
										<div class="md-tip-c">
											您有麦豆 <strong class="red">0</strong> 个，请输入想使用的麦豆数（10个起用，只可能使用10的整倍数），不使用请填0
										</div>
										<span class="arrow-t-l"></span>
									</div>
								</div>
							</div>							
							<div class="cart-count" id="order-total">
								<table>
									<tbody>
										<tr>
											<th>商品件数：</th>
											<td id="countsnub">0件</td>
										</tr>
										<tr>
											<th>商品总金额(不含运费)：</th>
											<td id="countprices">￥0.00</td>

										</tr>
										<tr>
											<th>麦豆抵扣：</th>
											<td id="mddk">-￥0.00</td>
										</tr>
										<tr>
											<th>运费：</th>
											<td id="yfprice">￥0.00</td>
										</tr>
										<tr>										
											<th colspan="2">
												<div class="frieight-tip">您可以享受免运费服务</div>
											</th>
										</tr>
										<tr>
											<th colspan="2">
												<div class="total-price">应付金额：<strong id="zgprice">￥0.00</strong></div>
											</th>
										</tr>

									</tbody>
								</table>
							</div>
							<div class="bottom-btns">
								<a href="{% url 'mbb:adv' %}" class="go-checkout"></a>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
		<div class="footer">
			<div class="footer-warp">
				<div class="special-service">
					<ul>
						<li><a href="javascript:void(0);" class="spe-ser-1"></a></li>
						<li><a href="javascript:void(0);" class="spe-ser-2"></a></li>
						<li><a href="javascript:void(0);" class="spe-ser-3"></a></li>
						<li><a href="javascript:void(0);" class="spe-ser-4"></a></li>
						<li><a href="javascript:void(0);" class="spe-ser-5"></a></li>
					</ul>
				</div>
				<div class="copyright">
					©2007-2012 Mbaobao All Rights Reserved. 嘉兴市麦宝科技信息有限公司 版权所有，禁止非法复制 <a href="javascript:void(0);" class="gray">经营许可证编号：浙B2-20100425</a>
				</div>
			</div>
		</div>
		<div class="fd-side">
			<ul>
				<li><a href="javascript:void(0);" class="chat"><i></i><span>在线咨询</span></a></li>
				<li><a href="{% url 'mbb:cart' %}" class="gocart"><i></i><span>去购物车</span></a></li>
				<li><a href="javascript:void(0);" class="qrcode">
					<div class="qrcode-hover-show"><img src="/static/img/index/ewm_02.png"/></div>
					<i></i><span>二维码</span></a>
				</li>
			</ul>
		</div>
	</body>
</html>

templates/login.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>登录-麦包包官方网站</title>
<link rel="stylesheet" type="text/css" href="../static/css/reset.css"/>
<link rel="stylesheet" type="text/css" href="../static/css/login.css"/>
<script type="text/javascript" src="../static/js/jquery-1.12.3.js"></script>
<script type="text/javascript" src="../static/js/login-jq.js"></script>
</head>
<body>
<div class="login-head">
	<div class="login-head-warp">
		<a href="{% url 'mbb:index' %}" class="logo"></a>
		<span>登录时遇到问题或有改进建议<a href="javascript:void(0);">点击这里反馈>></a></span>
	</div>
</div>
<div class="cont-warp">
	<a href="javascript:void(0);" class="login-link"><img src="../static/img/login/loginimg01.jpg"/></a>
	<div class="login-dialog">
		<div class="login-title">
			<h3 class="user-l">用户登录</h3>
			<span>现在还不是麦包包会员?<a href="{% url 'mbb:register' %}">立即注册</a></span>
		</div>
		<form action="" method="post" id="form-login">
        {% csrf_token %}
			<div class="login-error" id="login-error"><span>请填写手机号码或者邮箱</span></div>
			<ul class="dialog-main">
				<li><span>用户名：</span><input type="text" id="login-username" name="username"/>
                    <style>
                        #backspan{
                            font-size: 10px;
                            color: red;

                        }
                    </style>
                {% if num == 1 %}
                    <span id="backspan">账户不存在</span>
                {% elif num == 2 %}
                    <span id="backspan">密码错误</span>
                {% endif %}


                </li>
				<li><span>登录密码：</span><input type="password" id="login-pwd" name="password"/><a href="javascript:void(0);">找回密码</a></li>
				<li><span></span><input type="submit" value="马上登录" class="btn" datafld="datafld"/></li>  <script>
                            $('#login-username').focus(function(){
                                $('#backspan').hide()
                            })

                              $('#login-pwd').focus(function(){
                                $('#backspan').hide()
                            })

                        </script>
			</ul>
		</form>
		<div class="quick-login">
			<h4>使用合作网站帐号登录麦包包</h4>
			<div class="quick-main">
				<a href="javascript:void(0);" class="quick-zfb"></a>
				<a href="javascript:void(0);" class="quick-qq">QQ</a>｜<a href="javascript:void(0);" class="quick-sina">新浪微博</a>｜<a href="javascript:void(0);" class="quick-chinamobile">中国移动</a>｜<a href="javascript:void(0);" class="quick-weixin">微信</a>
			</div>
		</div>
	</div>
</div>
<div class="login-foot">
	<p>© 2007-2013 Mbaobao All Rights Reserved. 嘉兴市麦包包网络科技有限公司 版权所有，禁止非法复制 经营许可证编号：浙B2-20100425</p>
</div>
</body>
</html>

templates/myorder.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
	<title>我的购物车-麦包包</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css"/>
	<link rel="stylesheet" type="text/css" href="/static/css/cart.css"/>
	<script src="/static/js/jquery-1.12.3.js"></script>
	<script src="/static/js/jquery.cookie.js"></script>
	<script src="/static/js/cart-jq.js"></script>
        <link rel="stylesheet" type="text/css" href="/static/css/myorder.css"/>
        <script src="/static/js/myorder.js"></script>
        <link rel="stylesheet" href="/static/css/adv.css">
        <script src="/static/js/adv.js"></script>
        <style>
            .goods-list tbody tr td{
                text-align: center;
            }
            .goods-list thead tr td span{
                height: 30px;
                width: 30px;
                font-size: 30px;
                margin: 5px;
                cursor: pointer;
            }
        </style>
	</head>
	<body>

		<div class="cart-top">
			<div class="cart-warp">
				<a href="{% url 'mbb:index' %}" class="cart-logo"><img src="/static/img/index/logo.png"/></a>
				<div class="cart-title">
					<h1>购物车</h1>
					<div class="login-bar">您好，欢迎来到麦包包！</div>
				</div>
				<div class="cart-step">
					<div class="cart-step-icon"></div>
					<ul>
						<li><em class="red">1.确认采购商品</em></li>
						<li>2.填写收货信息</li>
						<li>3.支付</li>
						<li>4.支付成功</li>
					</ul>
				</div>
			</div>
		</div>

		<div class="container-bg-warp">
			<div class="container-warp">
				<div class="cart-notice">
					<strong>温馨提示：</strong>
					<p>加入购物车的商品无法为您保留库存，请及时下单购买，商品价格以订单提交时的价格为准。</p>
					<i class="arrow-b-l"></i>
				</div>

                <div class="cart-main">


                    <div id="js-goods-container">
                    <table border="1" cellspacing="0">

                    <tr>
                        <td width="500">订单号</td>
                        <td width="100">订单状态</td>
                        <td width="400">操作</td>
                 </tr>
                        {% for order in orders %}
                            <tr>
                            <td>{{ order.ordernum }}</td>
                                {% if order.status == 0 %}
                                     <td>未支付</td>
                                    <td isid="{{ order.id }}"><input type="button" value="取消订单" class="concer">&nbsp;<input type="button" value="支付" class="pay"  num="{{ order.ordernum }}"><input
                                            type="button" value="查看商品" class="detail"></td>
                                {% endif %}
                                {% if order.status == 1 %}

                                     <td>待发货</td>
                                    <td isid="{{ order.id }}"><input type="button" value="申请退货" class="tuihuo">&nbsp;<input type="button" value="提醒商家发货"><input
                                            type="button" value="查看商品" class="detail"></td>
                                {% endif %}
                                {% if order.status == 2 %}

                                     <td>待收货</td>
                                    <td isid="{{ order.id }}"><input type="button" value="申请退货" class="tuihuo">&nbsp;<input type="button" value='查看物流' class="cat">&nbsp;<input type="button" value='确认收货' class="reap"><input
                                            type="button" value="查看商品" class="detail"></td>
                                {% endif %}
                                {% if order.status == 3 %}

                                     <td>待评价</td>
                                    <td isid="{{ order.id }}"><input type="button" value="取消订单" class="concer">&nbsp;<input type="button" value="评价" class="eva"><input
                                            type="button" value="查看商品" class="detail"></td>
                                {% endif %}
                            {% if order.status == 4 %}
                              <td>已完成交易</td>
                                    <td isid="{{ order.id }}"><input type="button" value="售后/退货" class="hind">&nbsp;<input type="button" value="查看交易信息" class="eva"><input
                                            type="button" value="查看商品" class="detail"></td>
                                {% endif %}

                            </tr>
                        {% endfor %}

                        </table>

                    </div>

                </div>

			</div>
		</div>
		<div class="footer">
			<div class="footer-warp">
				<div class="special-service">
					<ul>
						<li><a href="javascript:void(0);" class="spe-ser-1"></a></li>
						<li><a href="javascript:void(0);" class="spe-ser-2"></a></li>
						<li><a href="javascript:void(0);" class="spe-ser-3"></a></li>
						<li><a href="javascript:void(0);" class="spe-ser-4"></a></li>
						<li><a href="javascript:void(0);" class="spe-ser-5"></a></li>
					</ul>
				</div>
				<div class="copyright">
					©2007-2012 Mbaobao All Rights Reserved. 嘉兴市麦宝科技信息有限公司 版权所有，禁止非法复制 <a href="javascript:void(0);" class="gray">经营许可证编号：浙B2-20100425</a>
				</div>
			</div>
		</div>
		<div class="fd-side">
			<ul>
				<li><a href="javascript:void(0);" class="chat"><i></i><span>在线咨询</span></a></li>
				<li><a href="{% url 'mbb:cart' %}" class="gocart"><i></i><span>去购物车</span></a></li>
				<li><a href="javascript:void(0);" class="qrcode">
					<div class="qrcode-hover-show"><img src="/static/img/index/ewm_02.png"/></div>
					<i></i><span>二维码</span></a>
				</li>
			</ul>
		</div>
	</body>
</html>

templates/select.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    		<script type="text/javascript" src="../static/js/jquery-1.12.3.js"></script>

    <style>
        .price_input{
            width: 60px;
        }
        .pro-list{text-align: center;}
        .pro-list ul{width: 990px;padding-left: 7px;padding-bottom: 10px;margin: 0 auto;text-align: left;overflow: hidden;}
        .pro-list li{width: 245px;position: relative;transition: all .3s ease;height: 310px;overflow: hidden;margin-top: 20px;float: left;}
        .pro-list li:hover{box-shadow: 0 0 15px rgba(0,0,0,.2);}
        .pro-list .pic{margin-bottom: 10px;margin: 0 auto;width: 174px;height: 174px;position: relative;display: block;}
        .pro-list .color-sel-box{text-align: left;margin: 10px 0 4px 16px;height: 28px;position: relative;}
        .color-sel-box .color-wrap{background: white;width: 178px;height: 24px;position: absolute;top:0;left: 0;}
        .color-sel-box a{margin: 0 5px 5px 0;display: inline-block;width: 22px;height: 22px;padding: 1px;}
        .color-sel-box a:hover{border: 1px solid #d41c4f;padding: 0;}
        .pro-info{line-height: 18px;color: #333;text-align: left;}
        .pro-info .name{display: block;width: 200px;margin: 0 auto;margin-bottom: 10px;color: #888;}
        .pro-info .name:hover{color: #ed1c22;}
        .pro-info .price{width: 170px;margin: 0 auto 0 23px;text-align: left;}
        .pro-info .price .price1{font-weight: 700;}
        .pro-info .price .price2{color: #b0b0b0;}

        .red, a.red, a.red:hover, a.red:visited{color: #d41c4f;font-family: tahoma,verdana,arial,helvetica,sans-serif;}
    </style>
</head>
<body>
<h2 style="text-align: center;margin: 0;padding: 0;"><input type="text" placeholder="最低价" class="price_input" id="text1">-<input type="text" placeholder="最高价" class="price_input" id="text2"> <button id="getgood">查询</button> </h2>
<div class="pro-list">
<ul class="show-type-style">

</ul>
    <script>
        //$('.result').remove()

        function f() {
            less=$('#text1').val()
            mast=$('#text2').val()
             $.get('/selectprice/',{'less':less,'mast':mast},function (response) {
                    console.log(response)
                    $('.show-type-style').html('')
                    if (response.msg == 0){
                        $('#text1').val('')

                        $('#text2').val('')
                    }
                    else {
                        goods = response.goods
                        for (i = 0;i < goods.length;i++){
                            good = goods[i]
                            $('.show-type-style').html($('.show-type-style').html()+'<li class="result"><a href="javascript:void(0);" class="pic mainpic"><img src='+good['img']+ ' width="174" height="174" title='+good['name']+' /></a><div class="color-sel-box"><div class="color-wrap"><a href="javascript:void(0);"><img src="../static/img/list/05-1-1.jpg" width="22" height="22" /></a></div></div><div class="pro-info"><a href="javascript:void(0);" class="name">'+good['name']+'</a><div class="price"><b class="red price1">￥'+good['price']+'</b><s class="price2">￥'+good['mppprice']+'</s></div></div></li>')
                        }
                    }
            })
        }
        f()
        $('#getgood').click(function () {


      //      if (less=="")
      //      if (isNaN(less)){
      //          less = 0
       //     }
            if (less > mast){
                console.log('erro')
            }

            f()
        })


    </script>
</div>
</body>
</html>

templates/uploadhead.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户详情</title>
</head>
<body>
<img src="{{ user.img }}" >
<p>用户名:{{ user.username }}</p>
<form action="/uploadhead/" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="heading"> <input type="submit" value="上传">



</form>
</body>
</html>